### DISCUSSION TITLE
NubesGen new architecture

### DISCUSSION THREAD

**Discussion by cmaneu** [microsoft/NubesGen#45] [Request for Comments]
# NubesGen re-architecture proposal

We've shipped V0.1 and our first public technical preview with what is our "MVP" (minimum viable product). To support our future roadmap, substantial architectural choices needs to be done. This document is here to detail these changes and to seek feedback from the first users and partners before starting implementation.

## Goals

- **Flexibility**: 
    - **Support more services**: 
    - **Support paid/partner offerings**:
    - **Support internal-only features/configurations**: 
    - **Support sovereign & on-premises regions**:
- **Composition**: 
    - **Different UIs**
    - **Different outputs**: Bicep, Pulumi, etc...
    - **Different CI/CD systems**: 
- **A more "open" product: 
    - Allowing external contributions more easily
    - Allowing public and private extensions

### A model

- Services: A service represent one (or more) resources deployed. Each service is a "deployment module" (a Terraform module, a bicep template, ...) that can be composed together. Services can output values
- Service type: we can have public and private service types
    - Public ones includes: hosting, database, storage, messaging, ...
    - You can extend Nubes to use private options - like a custom VM that you manage and that offer a "PaaS-like" experience for your users
    - There are "reserved" service types, like "compute", "database", "gitops", etc...

#### Service package

Each service is contained as a "package", which is a folder with the following files: 
- a Service YAML file
- The template files (as a Mustache template)

### A File format

NubesGen is an API, but we need to facilitate accessing this API: 
- For users without Infrastructure as code knowledge, they may want that NubesGen takes care of everything for them. 
- For supporting deployment of custom workflows with non-default values: let's say you want to help people deploy a famous CMS (Content Management System) with Nubes. All the default options are great but you need to add one environment variable, and the default database environment variable name needs to be changed.

> **Warning**: _Do NOT reinvent the wheel_
> The purpose of NubesGen is **not** to become yet another Infrastructure as Code dialect. 
> The sole purpose of this file format is to let users access the opinionated defaults and choices made within Nubes in an easy way. If you just want to spinup a new storage, then you should probably use another tool (AZ Cli, ARM, Bicep...)

```yaml
projectName: my-blazor-quiz
region: francecentral
resources:
- name: frontend
  type: webapp
  subtype: docker
  size: free
  docker: 
    registry: github
      username: cmaneu
      password: ${pipeline.secrets.github_registry_accesstoken} 
    image: cmaneu/my-blazor-quiz
  envVars: 
  - key: MONGO_CS
    value: ${quiz-db.connection_string}
- name: quiz-db
  type: cosmosdb-mongodb
  size: serverless
gitops: true
monitoring: true
traits: 
# Traits allows to change configuration cross-resources
  - type: security
    level: medium

```

### An API

**NubesGen is only an API**. As such, it should expose: 

- An API definition metadata: This will help our experiences to dynamically generate the UI.
- Accept data in several ways: simple GET parameters, a POST query, a JSON file, a YAML file, etc...

### A generation pipeline

The generation pipeline is a multi-step pipeline, allowing to generate a model prior to generating the files. This allows for several scenarios, including: 

- Generating a (visual) graph for the generated components,
- Computing the cost estimation of deployed resources,
- Doing some validation

This pipeline is composed of several steps, and developers can extend it: 
- Parameters parsing and validation: This phase parses the input against the service definitions loaded in the current app context, and validates them.
- Model assembling: As services can request other services, we're assembling all these parameters into a graph of objects to generate.
- Cross-concerns modifiers: We'll implement some cross-concerns modifiers, like security (enable Azure Defender), management (add a Tag, a resource lock, ...), monitoring (connect to an Azure Monitor workspace). This stage will go through all services and modify as needed the parameters
- Template generation: This stage will take individual templates and generate them
- Packaging & publishing: the API supports several ways of exporting, and may support more in the future. This stage takes the generated templates and send them to the destination (tar.gz and zip for now).

The last two stages can be parallelized.
